document.addEventListener('DOMContentLoaded', () => {
    const contentDiv = document.getElementById('content');
    const gameListDivs = document.querySelectorAll('.game-list');
    const softwareListDiv = document.querySelector('.software-list');
    const backButton = document.getElementById('back-button');
    const searchInput = document.getElementById('searchInput');
    const categoryHeaders = document.querySelectorAll('h2');
    const showMoreButtons = [];

// content.js
const games = {
    blur: `<center><h4>Blur</h4></center><center><a href="https://buzzheavier.com/fzbjmo1ll4eh"><button>Download</button></a></center><iframe width="560" height="315" src="https://www.youtube.com/embed/aOUzxg6yJSM?si=mlnY3HX6fagDVGNa" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe><div class="black-box" style="font-family: 'Rajdhani';"><p>Minimum requirements:</p><p>CPU: Intel(R) Pentium(R) 4 3.0 GHz or AMD Athlon(TM) 64 3200+</p><p>RAM: 1 GB</p><p>OS: Microsoft Windows XP/Vista/7</p><p>Video Card: NVIDIA GeForce 6600 or ATI Radeon X1300</p><p>DirectX: Version 9.0c</p><p>Network: Internet connection is required for online multiplayer</p><p>Additional Notes: Internet connection required for online multiplayer</p></div>`,
    racedrivergrid: `<center><h4>Racedriver: GRID</h4></center><center><a href="https://buzzheavier.com/25nfsdzri2p4"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani';"><p>Minimum requirements:OS: Microsoft Windows XP/Vista/7</p><p>Processor: Intel Core 2 Duo 2.4 GHz or AMD Athlon X2 4800+</p><p>Memory: 2 GB RAM</p><p>Graphics: NVIDIA GeForce 8800 or ATI Radeon HD 3800</p><p>DirectX: Version 9.0c</p><p>Network: Internet connection required for online multiplayer</p><p>Storage: 15 GB available space</p></div>`,
    bptub: `<center><h4>Burnout Paradise: The Ultimate Box</h4></center><center><a href="https://buzzheavier.com/guqb4p0ryvzy"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display;</p></div>`,
    flatout: `<center><h4>Flatout</h4></center><center><a href="https://buzzheavier.com/2ihgl9a3jv4q"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display;</p></div>`,
    wrc2: `<center><h4>WRC 2 FIA WORLD RALLY CHAMPIONSHIP</h4></center><center><a href="https://buzzheavier.com/6js22264o79m"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: idk</p></div>`,
    wrc3: `<center><h4>WRC 3 WORLD RALLY CHAMPIONSHIP</h4></center><center><a href="https://buzzheavier.com/rinf00uh63i8"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Duo / AMD Athlon 64 X2 or higher RAM: 2 GB RAM (XP) / 3 GB (Vista) / 4 GB (7) VIDEO CARD: 512 MB Video card with Pixel Shader 3.0: GeForce 9800 / Radeon HD 4800 series or higher DEDICATED VIDEO RAM: 512 MB PIXEL SHADER: 3.0 VERTEX SHADER: 3.0 OS: Windows XP (SP2) / Vista / 7</p></div>`,
    nfs2se: `<center><h4>NEED FOR SPEED II SE</h4></center><center><a href="https://buzzheavier.com/37sn8sme4lao"><button>Download</button></a><a href="https://1fichier.com/?g32w33y56qwtcq8n253c"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Runs Windows XP</p></div>`,
    nfsmw: `<center><h4>NEED FOR SPEED MOST WANTED</h4></center><center><a href="https://buzzheavier.com/vdcctqwritsr"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Pentium 4 or Athlon XP; CPU SPEED: 1.4 GHz; RAM: 256 MB; VIDEO CARD: 32 MB DirectX 9.0c compatible 3D video card (NVIDIA GeForce2 MX+ / ATI Radeon 7500+ / Intel 915+); TOTAL VIDEO RAM: 32 MB; DIRECTX VERSION: DirectX 9.0c; OS: Windows 2000/XP; FREE DISK SPACE: 3 GB</p></div>`,
    nfsc: `<center><h4>NEED FOR SPEED CARBON</h4></center><center><a href="https://buzzheavier.com/4z6wruhwizw0"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Pentium 4 or Athlon XP; CPU SPEED: 1.4 GHz; RAM: 256 MB; VIDEO CARD: 32 MB DirectX 9.0c compatible 3D video card (NVIDIA GeForce2 MX+ / ATI Radeon 7500+ / Intel 915+); TOTAL VIDEO RAM: 32 MB; DIRECTX VERSION: DirectX 9.0c; OS: Windows 2000/XP; FREE DISK SPACE: 3 GB</p></div>`,
    nfsu: `<center><h4>NEED FOR SPEED UNDERCOVER</h4></center><center><a href="https://buzzheavier.com/dek6gsto30y5"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Pentium 4 or Athlon XP; CPU SPEED: 1.4 GHz; RAM: 256 MB; VIDEO CARD: 32 MB DirectX 9.0c compatible 3D video card (NVIDIA GeForce2 MX+ / ATI Radeon 7500+ / Intel 915+); TOTAL VIDEO RAM: 32 MB; DIRECTX VERSION: DirectX 9.0c; OS: Windows 2000/XP; FREE DISK SPACE: 3 GB</p></div>`,
    nfstr: `<center><h4>NEED FOR SPEED THE RUN</h4></center><center><a href="https://buzzheavier.com/5sm8jnhii9tn"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: 2.4 GHz Intel Core 2 Duo or AMD Equivalent; RAM: 3 GB; VIDEO CARD: 512 MB RAM ATI Radeon 4870 or higher performance / 512 MB RAM NVIDIA GeForce 9800 GT or higher performance; DEDICATED VIDEO RAM: 512 MB; OS: Windows Vista SP2 32-bit; FREE DISK SPACE: 18 GB</p></div>`,
    nfsr: `<center><h4>NEED FOR SPEED RIVALS</h4></center><center><a href="https://buzzheavier.com/1remramlwnua"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel 2.4 GHz Core 2 Duo, AMD 2.6 GHz Athlon X2; RAM: 4 GB; VIDEO CARD: AMD Radeon HD 3870 512Mb or better, NVIDIA GeForce 8800 GT 512 Mb or better, Intel HD 4000 integrated 512Mb or better; DEDICATED VIDEO RAM: 512 MB; OS: Windows XP, Windows Vista (SP2), Windows 7; FREE DISK SPACE: 30 GB</p></div>`,
    nfsh: `<center><h4>NEED FOR SPEED HEAT</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: Windows 10; Processor (AMD): FX-6350 or equivalent; Processor (Intel): Core i5-3570 or equivalent; Memory: 8 GB; Graphics Card (AMD): Radeon 7970/Radeon R9 280x or equivalent; Graphics Card (Nvidia): GeForce GTX 760 or equivalent; Direct X: 11; Hard Drive Space: 50 GB</p></div>`,
    nfshpr: `<center><h4>NEED FOR SPEED HOT PURSUIT REMASTERED</h4></center><center><a href="https://buzzheavier.com/pmn3bx5kcvvw"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: Windows 10, 64 Bit; Processor (AMD): Phenom II X4 965; Processor (Intel): Core i3-2120; Memory: 8 GB; Graphics Card (AMD): Radeon HD 5870; Graphics Card (Nvidia): GeForce GTS 640; DirectX: Dx. 11 compatible video card or equivalent; Hard Drive Space: 45 GB</p></div>`,
    nfsp: `<center><h4>NEED FOR SPEED PAYBACK</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: 64-bit Windows 7 or later; CPU: Intel i3 6300 @ 3.8GHz (2 Cores, 4 Threads) or AMD FX 8150 @ 3.6GHz (8 Cores, 8 Threads); RAM: 6GB; HARD DRIVE: 30GB; VIDEO: NVIDIA GeForce® GTX 750 Ti or AMD Radeon™ HD 7850 or equivalent DX11 compatible GPU with 2GB of memory; DirectX: 11 Compatible video card or equivalent</p></div>`,
    driversf: `<center><h4>DRIVER SAN FRANCISCO</h4></center><center><a href="https://buzzheavier.com/jhqfsjtkgp8h"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Pentium D 3.0 GHz or AMD Athlon 64 X2 4400+ 2.2 GHz; RAM: 1 GB Windows XP / 2 GB Windows Vista - Windows 7; VIDEO CARD: 256 MB DirectX 9.0-compliant card with Shader Model 4.0 or higher (ATI RADEON HD 2600 XT / HD 3000 / HD 4000 / HD 5000 / HD 6000 series & NVIDIA GeForce 8600 GT / 9000 / 100 /200 / 300 / 400 / 500 series); TOTAL VIDEO RAM: 256 MB; OS: Windows XP / Windows Vista / Windows 7; FREE DISK SPACE: 10 GB</p></div>`,
    carxdro: `<center><h4>CARX DRIFT ONLINE</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS *: Windows 7, 8, 10; Processor: Intel i5 4590 or AMD Ryzen3 1200; Memory: 4 GB RAM; Graphics: 2 GB (GeForce 950GT / AMD R9 270); DirectX: Version 11; Storage: 6 GB available space</p></div>`,
    forzah3: `<center><h4>FORZA HORIZON 3</h4></center><center><a href="https://buzzheavier.com/u0y8ejy2376m"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i3-4170 @ 3.7Ghz OR Intel i5 750 @ 2.67Ghz; RAM: 8 GB; VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x; DEDICATED VIDEO RAM: 2 GB; OS: Windows 10 version 15063.0 or higher</p></div>`,
    forzah4: `<center><h4>FORZA HORIZON 4</h4></center><center><a href="https://buzzheavier.com/t91vg99m7zb8"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i3-4170 @ 3.7Ghz OR Intel i5 750 @ 2.67Ghz; RAM: 8 GB; VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x; DEDICATED VIDEO RAM: 2 GB; OS: Windows 10 version 15063.0 or higher</p></div>`,
    forzah5: `<center><h4>FORZA HORIZON 5</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i5-4460 or AMD Ryzen 3 1200 RAM: 8 GB VIDEO CARD: NVidia GTX 970 OR AMD RX 470 DEDICATED VIDEO RAM: 4096 MB OS: Windows 10 version 15063.0 or higher STORAGE: 350GB FREE (For the compressed file and the game)</p></div>`,
    tdu2: `<center><h4>Test Drive Ultimate 2</h4></center><center><a href="https://buzzheavier.com/1d9qrab25jw9"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel(R) Pentium(R) D Dual Core 3.4 GHz; RAM: 1 GB RAM for Windows XP, 2 GB RAM for Winodws Vista/7; VIDEO CARD: 3D hardware accelerator card required - 100% DirectX(R) 9.0c-compliant 256 MB video card and drivers (NVIDIA(R) GeForce(R) 6600 GT 256 MB RAM and better chipsets / ATI Radeon(TM) 1600XT 256 MB RAM and better chipsets); TOTAL VIDEO RAM: 256 MB; PIXEL SHADER: 3.0; VERTEX SHADER: 3.0; HARDWARE T&L: Yes; DIRECTX VERSION: DirectX(R) 9.0c (Included); OS: Microsoft(R) Windows(R) XP / Vista(R) / 7; FREE DISK SPACE: 14 GB of free hard drive space; SOUND CARD: Yes</p></div>`,
    carms2018: `<center><h4>CAR MECHANIC SIMULATOR 2018</h4></center><center><a href="https://buzzheavier.com/wnar6c0rqg1i"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i3-4170 @ 3.7Ghz OR Intel i5 750 @ 2.67Ghz; RAM: 8 GB; VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x; DEDICATED VIDEO RAM: 2 GB; OS: Windows 10 version 15063.0 or higher</p></div>`,
    carms2015: `<center><h4>CAR MECHANIC SIMULATOR 2015</h4></center><center><a href="https://buzzheavier.com/jurhvrltwp5c"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display;</p></div>`,
    carms2014: `<center><h4>CAR MECHANIC SIMULATOR 2014</h4></center><center><a href="https://buzzheavier.com/9kg3rrbgbf33"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display;</p></div>`,
    beamng: `<center><h4>BEAMNG.DRIVE 0.32.5</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display;</p></div>`,
    gitr: `<center><h4>GTI RACING</h4></center><center><a href="EXPIRED"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel(R) Pentium(R) D Dual Core 3.4 GHz; RAM: 1 GB RAM for Windows XP, 2 GB RAM for Winodws Vista/7; VIDEO CARD: 3D hardware accelerator card required - 100% DirectX(R) 9.0c-compliant 256 MB video card and drivers (NVIDIA(R) GeForce(R) 6600 GT 256 MB RAM and better chipsets / ATI Radeon(TM) 1600XT 256 MB RAM and better chipsets); TOTAL VIDEO RAM: 256 MB; PIXEL SHADER: 3.0; VERTEX SHADER: 3.0; HARDWARE T&L: Yes; DIRECTX VERSION: DirectX(R) 9.0c (Included); OS: Microsoft(R) Windows(R) XP / Vista(R) / 7; FREE DISK SPACE: 14 GB of free hard drive space; SOUND CARD: Yes</p></div>`,
    xpandr: `<center><h4>XPAND RALLY</h4></center><center><a href="https://buzzheavier.com/kqy6lvt6qa03"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel(R) Pentium(R) D Dual Core 3.4 GHz; RAM: 1 GB RAM for Windows XP, 2 GB RAM for Winodws Vista/7; VIDEO CARD: 3D hardware accelerator card required - 100% DirectX(R) 9.0c-compliant 256 MB video card and drivers (NVIDIA(R) GeForce(R) 6600 GT 256 MB RAM and better chipsets / ATI Radeon(TM) 1600XT 256 MB RAM and better chipsets); TOTAL VIDEO RAM: 256 MB; PIXEL SHADER: 3.0; VERTEX SHADER: 3.0; HARDWARE T&L: Yes; DIRECTX VERSION: DirectX(R) 9.0c (Included); OS: Microsoft(R) Windows(R) XP / Vista(R) / 7; FREE DISK SPACE: 14 GB of free hard drive space; SOUND CARD: Yes</p></div>`,
    xpandre: `<center><h4>XPAND RALLY EXTREME</h4></center><center><a href="https://buzzheavier.com/z53jgkbr202e"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel(R) Pentium(R) D Dual Core 3.4 GHz; RAM: 1 GB RAM for Windows XP, 2 GB RAM for Winodws Vista/7; VIDEO CARD: 3D hardware accelerator card required - 100% DirectX(R) 9.0c-compliant 256 MB video card and drivers (NVIDIA(R) GeForce(R) 6600 GT 256 MB RAM and better chipsets / ATI Radeon(TM) 1600XT 256 MB RAM and better chipsets); TOTAL VIDEO RAM: 256 MB; PIXEL SHADER: 3.0; VERTEX SHADER: 3.0; HARDWARE T&L: Yes; DIRECTX VERSION: DirectX(R) 9.0c (Included); OS: Microsoft(R) Windows(R) XP / Vista(R) / 7; FREE DISK SPACE: 14 GB of free hard drive space; SOUND CARD: Yes</p></div>`,
    barrof22: `<center><h4>BARRO F22</h4></center><center><a href="https://buzzheavier.com/fnwtu2vbhzzf"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: pentium/celeron, 4gb ram, intel hd graphics</p></div>`,
    postal3: `<center><h4>POSTAL 3</h4></center><center><a href="https://flashbang.sh/f/GVLQhEdB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Pentium 4 3.0 GHz; RAM: 2 GB for XP / 4 GB for Vista – Win 7; VIDEO CARD: DirectX 9 compatible video card with 128 MB, Shader model 2.0, ATI Radeon X800, NVIDIA GeForce 6600 or better; TOTAL VIDEO RAM: 128 MB; OS: Windows 7 / Vista / Vista64 / XP; FREE DISK SPACE: 16 GB</p></div>`,
    postal4: `<center><h4>POSTAL 4</h4></center><center><a href="https://flashbang.sh/f/GVLXafLB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS *: Windows 8 and 10; Processor: 2.5 GHz quad core processor; Memory: 8 GB RAM; Graphics: DirectX11 compatible graphics card w/ dedicated 2GB VRAM; DirectX: Version 11; Storage: 25 GB available space</p></div>`,
    hotlinem: `<center><h4>HOTLINE MIAMI</h4></center><center><a href="https://buzzheavier.com/d8d7gvgh8nhu"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i3-2140 @ 3.1Ghz OR Intel i5 750 @ 2.67Ghz; RAM: 8 GB; VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x; DEDICATED VIDEO RAM: 2 GB; OS: Windows 10 version 15063.0 or higher</p></div>`,
    hotlinem2: `<center><h4>HOTLINE MIAMI 2</h4></center><center><a href="https://buzzheavier.com/s4qsrju1it8t"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i3-2140 @ 3.1Ghz OR Intel i5 750 @ 2.67Ghz; RAM: 8 GB; VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x; DEDICATED VIDEO RAM: 2 GB; OS: Windows 10 version 15063.0 or higher</p></div>`,
    postal2: `<center><h4>POSTAL 2</h4></center><center><a href="https://buzzheavier.com/pl2qtdgwdo81"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Pentium III or AMD Athlon RAM: 128 MB VIDEO CARD: 32MB NVIDIA GeForce 2 or ATI Radeon 7500 DEDICATED VIDEO RAM: 32 MB OS: Windows XP FREE DISK SPACE: 1200 MB</p></div>`,
    hl: `<center><h4>HALF LIFE</h4></center><center><a href="https://buzzheavier.com/74r80rfhdp61"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>RAM: 96 MB VIDEO CARD: 16 MB video card DEDICATED VIDEO RAM: 16 MB OS: Windows XP</p></div>`,
    hl2: `<center><h4>HALF LIFE 2</h4></center><center><a href="https://flashbang.sh/f/GXHb9KFB8AA"><button>Download</button></a><a href="https://1fichier.com/?w2jseur8pdjn2jwk8sp9"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>CPU SPEED: 1.7 Ghz RAM: 512 MB VIDEO CARD: DirectX 8.1 level Graphics Card (requires support for SSE) OS: Windows 7, Vista, XP FREE DISK SPACE: 6500 MB</p></div>`,
    fallout: `<center><h4>FALLOUT</h4></center><center><a href="https://buzzheavier.com/zmcyg2eh33fo"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: Windows Processor: Pentium 90Mhz or faster Memory: 16 MB Graphics: SVGA Hard Drive: 565 MB</p></div>`,
    fallout2: `<center><h4>FALLOUT 2</h4></center><center><a href="https://buzzheavier.com/afz8dxu6su9b"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: Windows Processor: Pentium 90Mhz or faster Memory: 16 MB Graphics: SVGA Hard Drive: 565 MB</p></div>`,
    codbo: `<center><h4>COD BLACK OPS</h4></center><center><a href="https://flashbang.sh/f/GVQmUk7B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel® Core™2 Duo E6600 or AMD Phenom™ X3 8750 or better; RAM: 2 GB; VIDEO CARD: Shader 3.0 or better 256MB NVIDIA® GeForce® 8600GT / ATI Radeon® X1950Pro or better; DEDICATED VIDEO RAM: 256 MB; OS: Windows® Vista / XP / 7; FREE DISK SPACE: 12 GB</p></div>`,
    codmw2: `<center><h4>COD MODERN WARFARE 2</h4></center><center><a href="https://flashbang.sh/f/GU-I75aB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-3570 or AMD Ryzen 5 1600X; RAM: 8 GB; VIDEO CARD: NVIDIA GeForce GTX 960 or AMD Radeon RX 470; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 10 64-bit; FREE DISK SPACE: 25 GB</p></div>`,
    codmw3: `<center><h4>COD MODERN WARFARE 3</h4></center><center><a href="https://flashbang.sh/f/GVQmX_5B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-3570 or AMD Ryzen 5 1600X; RAM: 8 GB; VIDEO CARD: NVIDIA GeForce GTX 960 or AMD Radeon RX 470; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 10 64-bit; FREE DISK SPACE: 25 GB</p></div>`,
    falloutnv: `<center><h4>FALLOUT NEW VEGAS</h4></center><center><a href="https://flashbang.sh/f/GVMPK1HB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: Dual Core 2.0GHz; RAM: 2 GB; VIDEO CARD: NVIDIA GeForce 6600 GT, ATI 1300XT; DEDICATED VIDEO RAM: 64 MB; OS: Windows 7/Vista/XP; FREE DISK SPACE: 10 GB</p></div>`,
    ghostot: `<center><h4>GHOST OF TSUSHIMA</h4></center><center><a href="https://flashbang.sh/f/GUw39a7B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i3-7100 or AMD Ryzen 3 1200; RAM: 8 GB; VIDEO CARD: NVIDIA GeForce GTX 960 or AMD Radeon RX 5500 XT; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 10 64-bit; FREE DISK SPACE: 75 GB</p></div>`,
    gow2018: `<center><h4>GOD OF WAR: 2018</h4></center><center><a href="https://flashbang.sh/f/GZihdCixUAA"><button>Download</button></a><a href="https://1fichier.com/?j11mrgn6mumsflmo4y93"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel i5-2500k (4 core 3.3 GHz) or AMD Ryzen 3 1200 (4 core 3.1 GHz) RAM: 8 GB VIDEO CARD: NVIDIA GTX 960 (4 GB) or AMD R9 290X (4 GB) DEDICATED VIDEO RAM: 4 GB OS: Windows 10 64-bit FREE DISK SPACE: 70 GB</p></div>`,
    gowr: `<center><h4>GOD OF WAR: RAGNAROK</h4></center><center><a href="https://1fichier.com/?o747avi979425xhtex9d"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Minimum requirements: OS: Windows 10 64-bit Processor: Intel i5-4670k or AMD Ryzen 3 1200 Memory: 8 GB RAM Graphics: NVIDIA GTX 1060 (6GB) or AMD RX 5500 XT (8GB) or Intel Arc A750 DirectX: Version 12 Storage: 380 GB FREE (for compressed file and game when uncompressed)</p></div>`,
    nms: `<center><h4>No Man's Sky</h4></center><center><a href="https://flashbang.sh/f/GUzkAcQB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i3-7100 or AMD Ryzen 3 1200; RAM: 8 GB; VIDEO CARD: NVIDIA GeForce GTX 960 or AMD Radeon RX 5500 XT; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 10 64-bit; FREE DISK SPACE: 30 GB</p></div>`,
    bodycam: `<center><h4>BODYCAM</h4></center><center><a href="https://flashbang.sh/f/GU3CJKuB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD Ryzen 7 3700X, Intel Core i7-9700K; RAM: 8 GB; VIDEO CARD: AMD Radeon RX 5700 (8 GB), NVIDIA GeForce RTX 2070 (8 GB); DEDICATED VIDEO RAM: 8192 MB; OS: Windows 10/11; FREE DISK SPACE: 50 GB</p></div>`,
    deadpool: `<center><h4>DEADPOOL</h4></center><center><a href="https://flashbang.sh/f/GU8Pm_2B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Duo E8200 @ 2.66 GHz or AMD Phenom X3 8750; RAM: 2 GB; VIDEO CARD: GeForce 8800 GT series with 512 MB RAM or ATI Radeon HD4850 with 512MB RAM; DEDICATED VIDEO RAM: 512 MB; OS: Windows 8, Windows 7, Windows Vista, Windows XP; FREE DISK SPACE: 7 GB</p></div>`,
    eft: `<center><h4>ESCAPE FROM TARKOV</h4></center><center><a href="https://flashbang.sh/f/GVBG5gBB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: OS: Windows 7/8/10 (64 Bit); Processor:dual-core processor 2.4 GHz (Intel Core 2 Duo, i3), 2.6 GHz (AMD Athlon, Phenom II); RAM: 8 GB; Graphics Card: DX11 compatible graphics card with 1 GB memory; Sound: DirectX compatible audio card; Network: permanent connection to the Internet; Disk space: from 19 GB</p></div>`,
    srttr: `<center><h4>SAINTS ROW THE THIRD REMASTERED</h4></center><center><a href="https://flashbang.sh/f/GVKnJFoB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD FX 6200 / Intel Core i5-3570K or better; RAM: 8 GB; VIDEO CARD: 4 GB AMD Radeon 500 series or NVIDIA GeForce GTX 660 or newer; DEDICATED VIDEO RAM: 4 GB; OS: Windows 10 64-bit; FREE DISK SPACE: 46 GB</p></div>`,
    watchd1: `<center><h4>WATCH DOGS 1</h4></center><center><a href="https://flashbang.sh/f/GVQTmXWB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Quad Q8400 @ 2.66Ghz or AMD Phenom II X4 940 @ 3.0Ghz; RAM: 6 GB; VIDEO CARD: DirectX 11 graphics card with 1 GB Video RAM - Nvidia Geforce GTX 460 or AMD Radeon HD 5770 / Intel Iris Pro HD 5200; DEDICATED VIDEO RAM: 1 GB; OS: Windows Vista (SP2), Windows 7 (SP1) or Windows 8 (64 bit only); FREE DISK SPACE: 25 GB</p></div>`,
    maxp2: `<center><h4>MAX PAYNE 2</h4></center><center><a href="https://flashbang.sh/f/GWVJsPHB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: 1 Ghz PIII/Athlon or 1.2 Ghz Celeron/Duron processor; CPU SPEED: 1 Ghz PIII/Athlon or 1.2 Ghz Celeron/Duron processor; RAM: 256 MB; VIDEO CARD: 32 MB; DEDICATED VIDEO RAM: 32 MB; OS: Windows 98/ME/2000/XP; FREE DISK SPACE: 1.5 GB</p></div>`,
    maxp3: `<center><h4>MAX PAYNE 3</h4></center><center><a href="https://flashbang.sh/f/GWYBps0B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Dual Core 2.4 GHz / AMD Dual Core 2.6 GHz; RAM: 2 GB; VIDEO CARD: NVIDIA 8600 GT 512MB VRAM / Radeon HD 3400 512MB VRAM; DEDICATED VIDEO RAM: 512 MB; OS: Windows 7 32/64 Service Pack 1, Windows Vista 32/64 Service Pack 2, Windows XP 32/64 Service Pack 3; FREE DISK SPACE: 35 GB</p></div>`,
    rdr1: `<center><h4>RED DEAD REDEMPTION</h4></center><center><a href="https://buzzheavier.com/0dej7o99abpc"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel® Core™ i5-3470 / AMD FX-9590 RAM: 8 GB VIDEO CARD: NVIDIA GeForce GTX 660 / AMD Radeon R7 360 DEDICATED VIDEO RAM: 1024 MB OS: Windows 10 64-Bit</p></div>`,
    rdr2: `<center><h4>RED DEAD REDEMPTION 2</h4></center><center><a href="https://flashbang.sh/f/GWYViqGB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display; GPU with DirectX 12 support 2 GB of GPU memory	GPU with DirectX 12 support 4 GB of GPU memory</p></div>`,
    rust: `<center><h4>RUST</h4></center><center><a href="https://flashbang.sh/f/GU0GCqDB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i7-3770 / AMD FX-9590 or better; RAM: 8 GB; VIDEO CARD: GTX 670 2GB / AMD R9 280 better; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 7 64bit; FREE DISK SPACE: 10 GB</p></div>`,
    dayz: `<center><h4>DAYZ</h4></center><center><a href="https://flashbang.sh/f/GU-XN5IB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-4430; RAM: 8 GB; VIDEO CARD: NVIDIA GeForce GTX 760 or AMD R9 270X; DEDICATED VIDEO RAM: 2048 MB; OS: Windows 7/8.1 64-bit; FREE DISK SPACE: 16 GB</p></div>`,
    fnafsb: `<center><h4>FNAF SECURITY BREACH</h4></center><center><a href="https://flashbang.sh/f/GVk6aRNB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD Ryzen 5 3600, Core i5 6600K; RAM: 8 GB; VIDEO CARD: Nvidia GeForce GTX 1050 Ti; DEDICATED VIDEO RAM: 4096 MB; OS: Windows 10 (64 bit); FREE DISK SPACE: 70 GB</p></div>`,
    re6: `<center><h4>RESIDENT EVIL 6</h4></center><center><a href="https://flashbang.sh/f/GVlSVYcB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Duo 2.4 Ghz or better, AMD Athlon X2 2.8 Ghz or better; RAM: 2 GB; VIDEO CARD: NVIDIA GeForce 8800 GTS or better/Radeon HD 3870; DEDICATED VIDEO RAM: 256 MB; OS: Windows Vista/XP, Windows 7, Windows 8; FREE DISK SPACE: 16 GB</p></div>`,
    sev2r: `<center><h4>SNIPER ELITE V2 REMASTERED</h4></center><center><a href="https://flashbang.sh/f/GWu020cB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Operating System    Windows 7 SP1, 64-bit Processor    Intel CPU Core i3-2100 or AMD A8-5600K Memory    4 GB RAM Graphics    AMD Radeon HD 5570 (2GB) or NVIDIA GeForce GTX 650 (2GB) DirectX    Version 11 </p></div>`,
    whsm2: `<center><h4>WAR HAMMER: SPACE MARINE 2</h4></center><center><a href="https://flashbang.sh/f/GXSnweAB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>game .exe location: Warhammer 40000 - Space Marine 2\client_pc\root\bin\pc Space Marine 2 minimum requirements: Memory: 8 GB Graphics Card: NVIDIA GeForce GTX 1060 CPU: Intel Core i5-8600K File Size: 75 GB OS: Windows 10 or higher</p></div>`,
    gtasam: `<center><h4>GTA SAN ANDREAS MOBILE</h4></center><center><a href="https://flashbang.sh/f/GXStDjaB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: 2.6gb free storage</p></div>`,
    mcje: `<center><h4>MINECRAFT JAVA EDITION</h4></center><center><a href="https://drive.google.com/file/d/1UTPMlvIfj1oh1Q1whrxkSO8AVwVgPQLY/view?usp=sharing"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Are you serious? this game can even run on a mobile phone emulated.</p></div>`,
    mcbe: `<center><h4>MINECRAFT BEDROCK EDITION</h4></center><center><a href="https://bedrocklauncher.github.io/"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Their LOWER then Java Edition. go play java edition</p></div>`,
    f1m: `<center><h4>F1 MOBILE</h4></center><center><a href="https://drive.google.com/drive/mobile/folders/1ZnwQwCkdqrJ9DCBN1t8rnnWY8nAevGxs?usp=sharing"><button>APK Download</button></a> <a href="https://drive.google.com/drive/mobile/folders/1ZnwQwCkdqrJ9DCBN1t8rnnWY8nAevGxs?usp=sharing"><button>OBB File Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>INSTRUCTION: 1. Download both files, 2. Extract files from data zip folder (You'll need file explorer app like Zarchiver), 3. Copy data folder (it should be called com.codemasters.f12016) in Android -> OBB Folder, 4. Install the APK file and enjoy the game.</p></div>`,
    geometrydm: `<center><h4>GEOMETRY DASH MOBILE</h4></center><center><a href="https://flashbang.sh/f/GXXmaN6B8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: have android higher then android 7 ig</p></div>`,
    iriumwebcam: `<center><h4>IRIUM WEBCAM</h4></center><center><a href="https://cdn.discordapp.com/attachments/1284182930083811370/1284183256992059502/Iriun_Webcam_v2.8.7_Premium_-_Udiscord.apk?ex=66e65d1b&is=66e50b9b&hm=61d2652267f401948798dab162f80077ffa715e2cbd8818e2f28f05cbfc09e35&"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Use your phone as a webcam! download the irium pc program and it should work.</p></div>`,
    portal: `<center><h4>PORTAL</h4></center><center><a href="https://flashbang.sh/f/GXYg1yRB8AA"><button>Download</button></a><a href="https://1fichier.com/?i35nck3z9kfrwyl1r5w1"><button>Backup Download</button></a>"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: 1.7 GHz RAM: 512 MB VIDEO CARD: NVIDIA GeForce3+ / ATI Radeon 8500+ DEDICATED VIDEO RAM: 32 MB OS: Windows 7 (32/64-bit)/Vista/XP</p></div>`,
    portal2: `<center><h4>PORTAL 2</h4></center><center><a href="https://flashbang.sh/f/GXYnDmqB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: RAM: 2 GB VIDEO CARD: Video card must be 128 MB or more and with support for Pixel Shader 2.0b (ATI Radeon X800 or higher / NVIDIA GeForce 7600 or higher / Intel HD Graphics 2000 or higher). DEDICATED VIDEO RAM: 128 MB OS: Windows 7 / Vista / XP FREE DISK SPACE: 8 GB</p></div>`,
    watchd2: `<center><h4>WATCH DOGS 2</h4></center><center><a href="https://flashbang.sh/f/GX3N2oGB8AA"><button>Download</button></a><a href="https://1fichier.com/?ix1oqrz4yb0xgcypz1gn"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5 2400s @ 2.5 GHz, AMD FX 6120 @ 3.5 GHz or better RAM: 6 GB VIDEO CARD: NVIDIA GeForce GTX 660 with 2 GB VRAM or AMD Radeon HD 7870, with 2 GB VRAM or better DEDICATED VIDEO RAM: 2048 MB OS: Windows 7 SP1, Windows 8.1, Windows 10 (64bit versions only) FREE DISK SPACE: 50 GB</p></div>`,
    dbh: `<center><h4>DETROIT BECOME HUMAN</h4></center><center><a href="https://flashbang.sh/f/GX2r7fZB8AA"><button>Download</button></a><a href="https://1fichier.com/?um6vmdcaqft5y9nltu5h"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-2300 @ 2.8 GHz or AMD Ryzen 3 1200 @ 3.1GHz or AMD FX-8350 @ 4.2GHz RAM: 8 GB VIDEO CARD: Nvidia GeForce GTX 780 or AMD HD 7950 with 3GB VRAM minimum (Support of Vulkan 1.1 required) DEDICATED VIDEO RAM: 3072 MB OS: Windows 10 (64 bit) FREE DISK SPACE: 55 GB</p></div>`,
    msc: `<center><h4>MY SUMMER CAR</h4></center><center><a href="https://flashbang.sh/f/GXwZtP-B8AA"><button>Download</button></a><a href="https://1fichier.com/?jtof91bffiwzf4yk09qq"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: RAM: 4 GB VIDEO CARD: Nvidia GTX 650 TI or AMD equivalent DEDICATED VIDEO RAM: 1024 MB OS: 64bit versions of Windows 7, Windows 8, Windows 10 FREE DISK SPACE: 1 GB</p></div>`,
    pz: `<center><h4>PROJECT ZOMBOID</h4></center><center><a href="https://flashbang.sh/f/GXwWbumB8AA"><button>Download</button></a><a href="https://1fichier.com/?tz0qw39hgq9ilxsyet7l"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel 2.77 GHz Quad Core or equivalent RAM: 2 GB VIDEO CARD: OpenGL 2.1 compatible dedicated graphics card (GeForce 6600/Radeon 9500) OS: Windows XP, Vista, 7 FREE DISK SPACE: 1.23 GB</p></div>`,
    gamedt: `<center><h4>GAME DEV TYCOON</h4></center><center><a href="https://flashbang.sh/f/GXwTazzB8AA"><button>Download</button></a><a href="https://1fichier.com/?hpzamdbtq0yndp7oleml"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: RAM: 2 GB VIDEO CARD: Graphics hardware acceleration OS: Windows 7+</p></div>`,
    paperplease: `<center><h4>PAPERS PLEASE</h4></center><center><a href="https://flashbang.sh/f/GaC0YAAxUAA"><button>Download</button></a><a href="https://1fichier.com/?ep61r66h0tziq2dsg104"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: RUNS WINDOWS 10</p></div>`,
    gtasa: `<center><h4>GTA SAN ANDREAS</h4></center><center><a href="https://flashbang.sh/f/GXtJQpcB8AA"><button>Download</button></a><a href="https://1fichier.com/?hs3v95be6sq0ocdm9ccm"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: 1 Ghz RAM: 256 MB VIDEO CARD: 64 MB DirectX 8.1 compatible video card (NVIDIA GeForce 3 or better) TOTAL VIDEO RAM: 64 MB 3D: Yes OS: Windows 2000/XP only FREE DISK SPACE: 3.6 GB for minimal install</p></div>`,
    gta4: `<center><h4>GTA 4 + DLC</h4></center><center><a href="https://flashbang.sh/f/GaHQRR-xUAA"><button>Download</button></a><a href="https://1fichier.com/?xaf4kh1dei1hdqgli1o6"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Duo 1.8GHz, AMD Athlon X2 64 2.4GHz CPU SPEED: 1.8 GHz RAM: 1 GB for Windows XP / 1.5 GB for Windows Vista) VIDEO CARD: 256MB NVIDIA 7900+ / 256MB ATI X1900+ DEDICATED VIDEO RAM: 256 MB PIXEL SHADER: 3.0 VERTEX SHADER: 3.0 3D: Yes HARDWARE T&L: Yes OS: Windows Vista - Service Pack 1 / XP - Service Pack 3 / Windows 7</p></div>`,
    gmod11: `<center><h4>GMOD 11</h4></center><center><a href="https://flashbang.sh/f/GXTQ8YpB8AA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: 1.8 GHz Processor RAM: 2 GB VIDEO CARD: DirectX® 9 level Graphics Card (Requires support for SSE) OS: Windows® Vista/XP FREE DISK SPACE: 12 GB</p></div>`,
    firewatch: `<center><h4>FIREWATCH</h4></center><center><a href="https://buzzheavier.com/witqfvgh6c9q"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i3 2.00 GHz or AMD equivalent RAM: 6 GB VIDEO CARD: NVIDIA GeForce 450 or higher with 1GB Memory DEDICATED VIDEO RAM: 1 GB PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Windows 7 or higher 64bitFREE DISK SPACE: 4 GB </p></div>`,
    batmak: `<center><h4>BATMAN - ARKHAM KNIGHT</h4></center><center><a href="https://flashbang.sh/f/GaMh8IZxUAA"><button>Download</button></a><a href="https://1fichier.com/?syb8rffysarhus0y8as3"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-750, 2.67 GHz | AMD Phenom II X4 965, 3.4 GHz RAM: 6 GB VIDEO CARD: NVIDIA GeForce GTX 660 (2 GB Memory Minimum) | AMD Radeon HD 7950 (3 GB Memory Minimum) DEDICATED VIDEO RAM: 2 GB (3 GB AMD) PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Win 7 SP1, Win 8.1 (64-bit Operating System Required)</p></div>`,
    terraria: `<center><h4>TERRARIA</h4></center><center><a href="https://buzzheavier.com/kv3z67tlflfw"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: 2.0 Ghz RAM: 2.5 GB VIDEO CARD: 128mb Video Memory, capable of Shader Model 2.0+ DEDICATED VIDEO RAM: 128 MB PIXEL SHADER: 2.0 VERTEX SHADER: 2.0 OS: Windows Xp, Vista, 7, 8/8.1, 10</p></div>`,
    pokernati: `<center><h4>POKER NIGHT AT THE INVENTORY</h4></center><center><a href="https://buzzheavier.com/c6sivh5vp7hh"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: 2.0 GHz Pentium 4 or equivalent RAM: 3 GB VIDEO CARD: ATI or NVidia card w/512 MB RAM DEDICATED VIDEO RAM: 512 MB PIXEL SHADER: 4.0 VERTEX SHADER: 4.0 OS: Windows XP Service Pack 3</p></div>`,
    pokernati2: `<center><h4>POKER NIGHT AT THE INVENTORY 2</h4></center><center><a href="https://buzzheavier.com/k2zy8mhp8pba"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: 2.0 GHz Pentium 4 or equivalent RAM: 3 GB VIDEO CARD: ATI or NVidia card w/512 MB RAM DEDICATED VIDEO RAM: 512 MB PIXEL SHADER: 4.0 VERTEX SHADER: 4.0 OS: Windows XP Service Pack 3</p></div>`,
    undertale: `<center><h4>UNDERTALE</h4></center><center><a href="https://flashbang.sh/f/GaRjFt1xUAA"><button>Download</button></a><a href="https://1fichier.com/?39exhv7soxtar3sr9to4"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: RAM: 2 GB VIDEO CARD: Video Card with 128 MB OS: Windows XP, Vista, 7, 8, or 10</p></div>`,
    inscryption: `<center><h4>INSCRYPTION</h4></center><center><a href="https://buzzheavier.com/o29mz79wp8tz"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-760 (4 * 2800); AMD Athlon II X4 645 AM3 (4 * 3100) RAM: 4 GB VIDEO CARD: GeForce GTX 550 Ti (3072 VRAM); Radeon HD 6850 (1024 VRAM) DEDICATED VIDEO RAM: 3072 MB PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Windows 7</p></div>`,
    sonicxsg: `<center><h4>SONIC X SHADOW GENERATIONS (SWITCH EMU)</h4></center><center><a href="https://buzzheavier.com/ddjgqtbpwhx6"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i5-7500 RAM: 8 GB/ 16 GB RECOMMENDED VIDEO CARD: NVIDIA GeForce GTX 1050 TI / AMD Radeon RX 550 4GB OS: Windows 10+</p></div>`,
    hoi4: `<center><h4>HEARTS OF IRON IV (v1.15.1)</h4></center><center><a href="https://flashbang.sh/f/Ga1Slq0xUAA"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Quad Q9400 @ 2.66 GHz / AMD Athlon II X4 650 @ 3.20 GHz RAM: 4 GB VIDEO CARD: ATI Radeon HD 5850 or NVIDIA GeForce GTX470 with 1GB VRAM DEDICATED VIDEO RAM: 1024 MB PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Windows 7 64-bit or newer</p></div>`,
    victoria3: `<center><h4>Victoria 3 (1.8.6)</h4></center><center><a href="https://buzzheavier.com/mnolb41glocd"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel® Core™ i3-3250 or AMD® FX 8370 RAM: 8 GB VIDEO CARD: Nvidia® GeForce™ GTX 660 (2GB) or AMD® R7 370 (2GB) or Intel® HD Graphics 630 or AMD Radeon™ Vega 8 PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Windows® 10 Home 64 Bit</p></div>`,
    hitman3: `<center><h4>HITMAN 3</h4></center><center><a href="https://flashbang.sh/f/Ga4wxlPxUAA"><button>Download</button></a><a href="https://1fichier.com/?1ztzkk95f5o3pwexe9f3"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel CPU Core i5-2500K 3.3GHz / AMD CPU Phenom II X4 940 RAM: 8 GB VIDEO CARD: NVIDIA GeForce GTX 660 / Radeon HD 7870 DEDICATED VIDEO RAM: 2048 MB PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: OS 64-bit Windows 7</p></div>`,
    eldenr: `<center><h4>ELDEN RING</h4></center><center><a href="https://flashbang.sh/f/GbXcVFfxUAA"><button>Download</button></a><a href="https://1fichier.com/?vqiub6r16z2m0iu8phxg"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: CPU: Intel Core i5-8400 | AMD Ryzen 3 3300X RAM: 12 GB VIDEO CARD: Nvidia GeForce GTX 1060, 3GB | AMD Radeon RX 580, 4GB DEDICATED VIDEO RAM: 3 GB (4GB AMD) OS: Windows 10</p></div>`,
    cotl: `<center><h4>CULT OF THE LAMB</h4></center><center><a href="https://flashbang.sh/f/Gaqog1ixUAA"><button>Download</button></a><a href="https://1fichier.com/?056mq79e3hamjxfce971"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core i3-3240 (2 * 3400); AMD FX-4300 (4 * 3800) RAM: 4 GB VIDEO CARD: GeForce GTX 560 Ti (1024 VRAM); Radeon HD 7750 (1024 VRAM) DEDICATED VIDEO RAM: 1024 MB PIXEL SHADER: 5.0 VERTEX SHADER: 5.0 OS: Windows 7 or later</p></div>`,
    fnaf1m: `<center><h4>FNAF 1</h4></center><center><a href="https://flashbang.sh/f/GX6l40jB8AA"><button>Download</button></a></center>`,
    fnaf2m: `<center><h4>FNAF 2</h4></center><center><a href="https://flashbang.sh/f/GXwE4TmB8AA"><button>Download</button></a></center>`,
    fnaf3m: `<center><h4>FNAF 3</h4></center><center><a href="https://flashbang.sh/f/GXwFR26B8AA"><button>Download</button></a></center>`,
    fnaf4m: `<center><h4>FNAF 4</h4></center><center><a href="https://flashbang.sh/f/GXwF3CNB8AA"><button>Download</button></a></center>`,
    fnafslm: `<center><h4>FNAF SISTER LOCATION</h4></center><center><a href="https://flashbang.sh/f/GXwGK57B8AA"><button>Download</button></a></center>`,
    fnaf1: `<center><h4>FNAF 1</h4></center><center><a href="https://buzzheavier.com/wzey34o0kd2r"><button>Download</button></a></center>`,
    fnaf2: `<center><h4>FNAF 2</h4></center><center><a href="https://buzzheavier.com/nl6lgs8ma3n0"><button>Download</button></a></center>`,
    fnaf3: `<center><h4>FNAF 3</h4></center><center><a href="https://buzzheavier.com/qfy6fvn4qoxl"><button>Download</button></a></center>`,
    fnaf4: `<center><h4>FNAF 4</h4></center><center><a href="https://buzzheavier.com/sjesnin9wszt"><button>Download</button></a></center>`,
    doom12: `<center><h4>DOOM + DOOM II</h4></center><center><a href="https://buzzheavier.com/uieeulmso1nw"><button>Download</button></a></center>`,
    fnafsisterlocation: `<center><h4>FNAF SISTER LOCATION</h4></center><center><a href="https://buzzheavier.com/x2lsviwo0i9r"><button>Download</button></a></center>`,
    fnafucnm: `<center><h4>FNAF ULTIMATE CUSTOM NIGHT</h4></center><center><a href="https://flashbang.sh/f/GXwKXIaB8AA"><button>Download</button></a></center>`,
    dirt2: `<center><h4>DIRT 2</h4></center><center><a href="https://buzzheavier.com/9db5tyk7hje6"><button>Download</button></a><a href="https://buzzheavier.com/o7m80yk6tvz7"><button>ORIGINAL REPACK FILES</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD Athlon 64 X2, Pentium D 3.0 GHz RAM: 1GB RAM (2GB Vista) VIDEO CARD: NVIDIA GeForce 6800 + / ATI Radeon X1500+ TOTAL VIDEO RAM: 128 MB OS: Windows XP, Vista, 7</p></div>`,
    dirt3: `<center><h4>DIRT 3</h4></center><center><a href="https://buzzheavier.com/487d5oza5yua"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD Athlon 64 X2 2.8 GHz, Intel Pentium D 2.8 GHz RAM: 2 GB VIDEO CARD: AMD Radeon HD 2000 256 MB, NVIDIA GeForce 8000 Series 256 MB DEDICATED VIDEO RAM: 256 MB OS: Microsoft Windows XP, Vista or Windows 7</p></div>`,
    dirtr: `<center><h4>DIRT RALLY</h4></center><center><a href="https://buzzheavier.com/idzxmkq89qcz"><button>part 1</button></a><a href="https://buzzheavier.com/mto6a16lqz1i"><button>part 2</button></a><a href="https://buzzheavier.com/yts2te4igaac"><button>part 3</button></a><a href="https://buzzheavier.com/bvqp3l2910m6"><button>part 4</button></a></center><iframe class="rumble" width="640" height="360" src="https://rumble.com/embed/v663727/?pub=3u4il9" frameborder="0" allowfullscreen></iframe><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD FX Series or Intel Core i3 Series RAM: 4 GB VIDEO CARD: AMD HD5450 or Nvidia GT430 or Intel HD4000 with 1GB of VRAM (DirectX 11 graphics card required) DEDICATED VIDEO RAM: 1 GB OS: 64bit Versions of Windows 7, Windows 8, Windows 10</p></div>`,
    assassincs: `<center><h4>Assassin's Creed Syndicate</h4></center><center><a href="https://buzzheavier.com/5cjirk3tcc6z"><button>part 1</button></a><a href="https://buzzheavier.com/9gi7mqi9b6p1"><button>part 2</button></a><a href="https://buzzheavier.com/8vuvvonzzh87"><button>part 3</button></a><a href="https://buzzheavier.com/qv9snue1s56y"><button>part 4</button></a><a href="https://buzzheavier.com/v2frbhmgvuco"><button>part 5</button></a></center><iframe class="rumble" width="640" height="360" src="https://rumble.com/embed/v663727/?pub=3u4il9" frameborder="0" allowfullscreen></iframe><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: AMD FX Series or Intel Core i3 Series RAM: 4 GB VIDEO CARD: AMD HD5450 or Nvidia GT430 or Intel HD4000 with 1GB of VRAM (DirectX 11 graphics card required) DEDICATED VIDEO RAM: 1 GB OS: 64bit Versions of Windows 7, Windows 8, Windows 10</p></div>`,
    mxvsatv: `<center><h4>MX vs. ATV Supercross Encore</h4></center><center><a href="https://buzzheavier.com/tmwor4bi5pw0"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: Intel Core 2 Duo @ 1.8Ghz / AMD Athlon 64 X2 equivalent RAM: 2 GB VIDEO CARD: DirectX 10 compatible graphics card like Intel HD 3000, NVIDIA GeForce GTS 240 (1GB VRAM) or ATI Radeon HD 4600 (1GB VRAM) DEDICATED VIDEO RAM: 1 GB PIXEL SHADER: 4.0 VERTEX SHADER: 4.0 OS: Windows Vista, Windows 7, Windows 8 FREE DISK SPACE: 5 GB</p></div>`,
    ultrakill: `<center><h4>Ultrakill</h4></center><center><a href="https://buzzheavier.com/z1ryurzgkioi"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU SPEED: 2.4GHZ Dual Core Processor Or Higher RAM: 2 GB VIDEO CARD: GeForce 9800GT Or Equivalent DEDICATED VIDEO RAM: 512 MB PIXEL SHADER: 4.0 VERTEX SHADER: 4.0 OS: Windows 7 64-bit or later FREE DISK SPACE: 2 GB</p></div>`,
    mcb: `<center><h4>Browser Minecraft (Eaglecraft)</h4></center><center><a href="https://eaglercraft.com/mc/1.8.8/"><button>play</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Eaglecraft Server IP List: ArchMC - wss://mc.arch.lol TimeLegacy - wss://mc.time-legacy.net/ Asspixel Network - wss://mc.asspixel.net VanillaMC Legacy - wss://vanillamc.me noBnoT Anarchy - wss://eagler.nobnot.org</p></div>`
};

const software = {
    wengine: `<center><h4>Wallpaper Engine</h4><a href="https://buzzheavier.com/c5xtv20gn8q9"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: CPU: 1.66 GHz Intel i5 or equivalent; RAM: 1024 MB; VIDEO CARD: HD Graphics 4000 or above; OS: Windows 7 (with Aero), 8.1, 10; FREE DISK SPACE: 512 MB</p></div>`,
    vegas18: `<center><h4>Vegas 18.0</h4><a href="https://buzzheavier.com/duinxxt2rbx7"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Requires a 64-bit processor and operating system OS: Windows 10 (64-bit) Processor: 2 GHz Memory: 8 GB RAM Graphics: Supports NVIDIA, AMD/ATI or Intel GPU Storage: 1500 MB available space Sound Card: Multi-channel sound card recommended for surround sound editing</p></div>`,
    vegas22: `<center><h4>Vegas 22.0</h4><a href="https://buzzheavier.com/b4fglnejtir4"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display; GPU with DirectX 12 support 2 GB of GPU memory	GPU with DirectX 12 support 4 GB of GPU memory</p></div>`,
    vegass: `<center><h4>Vegas datamosh script</h4><a href="https://buzzheavier.com/d0nykdiq3q3j"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>requirements: have a version of Vegas 15.0+</p></div>`,
    spotify: `<center><h4>Spotify Ad Block</h4><a href="https://spicetify.app/docs/getting-started/"><button>Get</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>You need spotify to use this</p></div>`,
    flstudio: `<center><h4>FL Studio</h4><a href="https://buzzheavier.com/8nb263r8gwwi"><button>Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Windows 10 or 11 4GB free disk space 4GB of RAM The more powerful your CPU, the more instruments and effects you can run Intel and AMD CPUs. ARM not supported</p></div>`,
    msoffice: `<center><h4>Microsoft Office</h4><a href="https://massgrave.dev/genuine-installation-media"><button>Download Office</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>1. Open PowerShell (Not CMD). To do that, right-click on the Windows start menu and select PowerShell or Terminal. 2. Copy and paste the code below and press enter (if it doesnt work go to the original link and get the new one if its changed(also tell us if it is not working)) " irm https://get.activated.win | iex " 3. Download office from https://massgrave.dev/genuine-installation-media 4. After downloading office run the script in powershell 5. Select office OHook hack and let it do its thing to activate office on your computer 6. Enjoy free office for you studies or smt!</p></div>`,
    activatew: `<center><h4>Activate Windows</h4><a href="https://massgrave.dev/genuine-installation-media"><button>Windows Iso's</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>1. Open PowerShell (Not CMD). To do that, right-click on the Windows start menu and select PowerShell or Terminal. 2. Copy and paste the code below and press enter (if it doesnt work go to the original link and get the new one if its changed(also tell us if it is not working)) " irm https://get.activated.win | iex " 3. Select activate windows and it should do its thing!</p></div>`,
    photoshop: `<center><h4>Photoshop C6 13.0.1</h4><a href="https://flashbang.sh/f/GWTOXeWB8AA"><button>Download</button></a><a href="https://1fichier.com/?o34q0fm61r510fikdt5m"><button>Backup Download</button></a></center><div class="black-box" style="font-family: 'Rajdhani', sans-serif;"><p>Minimum requirements: Processor	Intel or AMD processor with 64-bit support; 2 GHz or faster processor with SSE 4.2 or later; Operating System	Windows 10 (64-bit) version 1809 or later; LTSC versions are not supported; RAM	8 GB	16 GB or more; Hard disk	~5 GB of available space (SSD); Monitor resolution	1280 x 800 display	1920 x 1080 display; GPU with DirectX 12 support 2 GB of GPU memory	GPU with DirectX 12 support 4 GB of GPU memory</p></div>`
};

    // Show only the first 6 items by default and add "Show More" functionality
    const addShowMoreButton = (list) => {
        const items = Array.from(list.children);

        if (items.length > 6) {
            const showMoreButton = document.createElement('button');
            showMoreButton.textContent = "Show More";
            showMoreButton.style.display = "block";
            showMoreButton.style.margin = "10px auto";

            // Hide all items after the first 6
            items.slice(6).forEach(item => {
                item.style.display = 'none';
            });

            // Add button and functionality to show hidden items
            list.after(showMoreButton);
            showMoreButton.addEventListener('click', () => {
                items.slice(6).forEach(item => {
                    item.style.display = 'block';
                });
                showMoreButton.style.display = 'none';
            });

            showMoreButtons.push(showMoreButton);
        }
    };

    gameListDivs.forEach(addShowMoreButton);
    if (softwareListDiv) addShowMoreButton(softwareListDiv);

    // Search functionality
    searchInput.addEventListener('input', () => {
        const searchTerm = searchInput.value.toLowerCase();
        let hasResults = false;

        gameListDivs.forEach(list => {
            let visibleGames = 0;
            Array.from(list.children).forEach(gameItem => {
                const gameName = gameItem.querySelector('h4').textContent.toLowerCase();
                if (gameName.includes(searchTerm)) {
                    gameItem.style.display = 'block';
                    visibleGames++;
                    hasResults = true;
                } else {
                    gameItem.style.display = 'none';
                }
            });
            list.style.display = visibleGames > 0 ? 'grid' : 'none';
        });

        let visibleSoftware = 0;
        Array.from(softwareListDiv.children).forEach(softwareItem => {
            const softwareName = softwareItem.querySelector('h4').textContent.toLowerCase();
            if (softwareName.includes(searchTerm)) {
                softwareItem.style.display = 'block';
                visibleSoftware++;
                hasResults = true;
            } else {
                softwareItem.style.display = 'none';
            }
        });
        softwareListDiv.style.display = visibleSoftware > 0 ? 'grid' : 'none';

        categoryHeaders.forEach(header => {
            header.style.display = searchTerm !== '' ? 'none' : 'block';
        });
    });

    // Hide "Show More" buttons
    const hideShowMoreButtons = () => {
        showMoreButtons.forEach(button => {
            button.style.display = 'none';
        });
    };

    // Show "Show More" buttons
    const showShowMoreButtons = () => {
        showMoreButtons.forEach(button => {
            if (button.style.display === 'none') {
                button.style.display = 'block';
            }
        });
    };

    // Show selected game
    document.querySelectorAll('.game-item').forEach(item => {
        item.addEventListener('click', () => {
            const game = item.dataset.game;
            if (games[game]) {
                contentDiv.innerHTML = games[game];
                backButton.style.display = 'block';

                categoryHeaders.forEach(header => header.style.display = 'none');
                gameListDivs.forEach(list => list.style.display = 'none');
                softwareListDiv.style.display = 'none';
                hideShowMoreButtons();
                window.scrollTo(0, 0);
            }
        });
    });

    // Show selected software
    document.querySelectorAll('.software-item').forEach(item => {
        item.addEventListener('click', () => {
            const softwareKey = item.dataset.software;
            if (software[softwareKey]) {
                contentDiv.innerHTML = software[softwareKey];
                backButton.style.display = 'block';

                categoryHeaders.forEach(header => header.style.display = 'none');
                gameListDivs.forEach(list => list.style.display = 'none');
                softwareListDiv.style.display = 'none';
                hideShowMoreButtons();
                window.scrollTo(0, 0);
            }
        });
    });

    // Back button to return to list
    backButton.addEventListener('click', () => {
        contentDiv.innerHTML = '';
        backButton.style.display = 'none';
        window.scrollTo(0, 0);

        categoryHeaders.forEach(header => header.style.display = 'block');
        gameListDivs.forEach(list => list.style.display = 'grid');
        softwareListDiv.style.display = 'grid';
        showShowMoreButtons();
    });

            // Scroll to header when searching
            window.scrollTo(0, 0);
        });
